BingMapKey: <%= ENV['BingMapKey'] %>

SourceCodeRepositoryUrl: 'https://github.com/TylerLu/EDUGraphAPI-Ruby'

AAD:
  ClientId: <%= ENV['ClientId'] %>
  ClientSecret: <%= ENV['ClientSecret'] %>

db:
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_DATABASE'] %>