
default_password: '111111'

redirect_uri: '/auth/azure_oauth2/callback'

BingMapKey: <%= ENV['BingMapKey'] %>

edu_graph_api:
  app_id: <%= ENV['ClientId']  %>
  default_key: <%= ENV['ClientSecret'] %>

db:
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_DATABASE'] %>