BingMapKey: <%= ENV['BingMapKey'] || "Anu3xoioQvqyG6b3eZ30IyR8TwyeQYpeag6OBdQvrsfUn0FwsVwFH9OnkJZvX-8a" %>

SourceCodeRepositoryUrl: 'https://github.com/TylerLu/EDUGraphAPI-Ruby'

AAD:
  ClientId: <%= ENV['ClientId'] || "70288edd-ba06-4139-befc-1315f6b0a721" %>
  ClientSecret: <%= ENV['ClientSecret'] || 'S01BulKmE3s4nPR9pJU7GzRlefCOGwqTu1Zbp3KsUvk=' %>

db:
  host: <%= ENV['DB_HOST'] || 'ap-cdbr-azure-east-a.cloudapp.net' %>
  username: <%= ENV['DB_USERNAME'] || 'b23685d7324082' %>
  password: <%= ENV['DB_PASSWORD'] || 'a01e0545' %>
  database: <%= ENV['DB_DATABASE'] || 'acsm_59b65ecb82b6e12' %>